version: 2
sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: gnosis_blocks
      - name: gnosis_txs
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'GNOSIS' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: address_labels
      - name: ez_hourly_prices
      - name: dim_labels
      - name: ez_hourly_token_prices
  - name: ethereum
    database: ethereum
    schema: core
    tables:
      - name: fact_hourly_token_prices
      - name: ez_hourly_token_prices
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'GNOSIS' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: near_address_encoded
      - name: labels_combined
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "GNOSIS_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "GNOSIS" }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: debug_traceBlockByNumber
      - name: decoded_logs
      - name: confirm_blocks
  - name: gnosis_silver
    database: gnosis
    schema: silver
    tables:
      - name: verified_abis
  - name: gnosis_bronze_api
    database: gnosis
    schema: bronze_api
    tables:
      - name: contract_abis
  - name: github_actions
    database: gnosis
    schema: github_actions
    tables:
      - name: workflows
  - name: external_gold_defillama
    database: external
    schema: defillama
    tables:
      - name: dim_chains