version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: gnosis_blocks
      - name: gnosis_txs
  - name: crosschain
    database: crosschain
    schema: core
    tables:
      - name: address_labels
      - name: ez_hourly_prices
  - name: ethereum
    database: ethereum
    schema: core
    tables:
      - name: fact_hourly_token_prices
  - name: streamline_crosschain
    database: streamline
    schema: crosschain
    tables:
      - name: node_mapping
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: apis_keys
      - name: token_prices_priority_hourly
      - name: asset_metadata_priority
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "GNOSIS_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "GNOSIS" }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: debug_traceBlockByNumber
      - name: decoded_logs
      - name: confirm_blocks
      